name: Compile and Run las.h tests
on: [push, pull_request]

jobs:
  windows:
    strategy:
      matrix:
        cc: [gcc, clang]
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Compile las tests
        run: ${{ matrix.cc }} -O2 -std=c89 -pedantic -Wall -Wextra -Werror -Wvla -Wconversion -Wdouble-promotion -Wsign-conversion -Wuninitialized -Winit-self -Wunused -Wunused-macros -Wunused-local-typedefs -o las_test_${{ matrix.cc }}.exe tests/las_test.c
      - name: Run las tests
        run: .\las_test_${{ matrix.cc }}.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-latest-${{ matrix.cc }}-las_test
          path: las_test_${{ matrix.cc }}.exe
